- src/Chain/GRBit.vcxproj
- src/Chain/GRBit.vcxproj.filters
- src/Chain/libraries/client/Client.cpp
- src/Chain/libraries/contract/rpc_mgr.cpp
- src/Chain/libraries/include/client/Client.hpp
- src/Chain/libraries/include/client/ClientImpl.hpp
- src/Chain/libraries/include/contract/rpc_message.hpp
- src/Chain/libraries/include/contract/rpc_mgr.hpp
- src/Chain/libraries/include/contract/task.hpp
add rpc client for lvm: 
modified:   src/Chain/GRBit.vcxproj
modified:   src/Chain/GRBit.vcxproj.filters
modified:   src/Chain/libraries/client/Client.cpp
modified:   src/Chain/libraries/include/client/Client.hpp
modified:   src/Chain/libraries/include/client/ClientImpl.hpp
new file:   src/Chain/libraries/include/contract/rpc_message.hpp
new file:   src/Chain/libraries/include/contract/rpc_mgr.hpp
new file:   src/Chain/libraries/include/contract/task.hpp
new file:   src/Chain/libraries/contract/rpc_mgr.cpp
> add rpc client for lvm

- src/Chain/libraries/contract/rpc_mgr.cpp
set  rpc_ip and rpc_port via configfile or other
> delete hard code,set rpc_ip,rpc_port

- src/Chain/libraries/blockchain/ChainDatabase.cpp
- src/Chain/libraries/client/BlockchainApi.cpp
- src/Chain/libraries/include/api/CommonApi.hpp
- src/Chain/libraries/include/blockchain/AccountOperations.hpp
- src/Chain/libraries/include/blockchain/ChainDatabase.hpp
- src/Chain/libraries/include/blockchain/Operations.hpp
- src/Chain/libraries/include/rpc_stubs/CommonApiClient.hpp
- src/Chain/libraries/include/rpc_stubs/CommonApiOverrides.ipp
- src/Chain/libraries/include/rpc_stubs/CommonApiRpcClient.hpp
- src/Chain/libraries/include/rpc_stubs/CommonApiRpcServer.hpp
- src/Chain/libraries/rpc_stubs/CommonApiClient.cpp
- src/Chain/libraries/rpc_stubs/CommonApiRpcClient.cpp
- src/Chain/libraries/rpc_stubs/CommonApiRpcServer.cpp
add Contract RPC "blockchain_get_contract_result" ++ Format the code
blockchain_get_contract_result <Call_Contract RequestId>
> add Contract RPC "blockchain_get_contract_result" ++ Format the code

- src/Chain/libraries/include/contract/task.hpp
> update contractops struct

- src/Chain/libraries/blockchain/ContractOperations.cpp
add  4 contractoperations : TransferTask / UpgradeTask / DestroyTask / CallTask
>  add interact interface into evaluate api

- src/Chain/libraries/blockchain/ContractOperations.cpp
modify the get_contract_entry in contract evalte function
> modify the get_contract_entry

- src/Chain/libraries/contract/rpc_mgr.cpp
- src/Chain/libraries/wallet/Wallet.cpp
move lock_guard and remove useless code
>  move lock_guard and remove useless code

- src/Chain/libraries/blockchain/ContractOperations.cpp
- src/Chain/libraries/contract/rpc_mgr.cpp
> add exception handling code

- src/Chain/libraries/contract/task_dispatcher.cpp
- src/Chain/libraries/include/contract/task.hpp
- src/Chain/libraries/include/lvm/lvm_interface.h
- src/Chain/libraries/lvm/lvm_interface.cpp
better the code of handling lua_request
> better the code of handling lua_request

- src/Chain/libraries/client/ContractApi.cpp
- src/Chain/libraries/client/WalletApi.cpp
- src/Chain/libraries/include/api/CommonApi.hpp
- src/Chain/libraries/include/rpc_stubs/CommonApiClient.hpp
- src/Chain/libraries/include/rpc_stubs/CommonApiOverrides.ipp
- src/Chain/libraries/include/rpc_stubs/CommonApiRpcClient.hpp
- src/Chain/libraries/include/rpc_stubs/CommonApiRpcServer.hpp
- src/Chain/libraries/include/wallet/Wallet.hpp
- src/Chain/libraries/rpc_stubs/CommonApiClient.cpp
- src/Chain/libraries/rpc_stubs/CommonApiRpcClient.cpp
- src/Chain/libraries/rpc_stubs/CommonApiRpcServer.cpp
- src/Chain/libraries/wallet/Wallet.cpp
add api create_transfer_transaction && call_contract_local_emit
> add api create_transfer_transaction && call_contract_local_emit

- src/Chain/libraries/blockchain/ContractOperations.cpp
- src/Chain/libraries/contract/task_dispatcher.cpp
- src/Chain/libraries/include/contract/task_dispatcher.hpp
- src/Chain/libraries/include/lvm/lvm_interface.h
- src/Chain/libraries/lvm/lvm_interface.cpp
add storage into the task_dispacher cache
> add storage into the dispacher cache

- src/Chain/libraries/blockchain/ContractOperations.cpp
- src/Chain/libraries/contract/task_dispatcher.cpp
- src/Chain/libraries/include/contract/task_dispatcher.hpp
- src/Chain/libraries/include/lvm/lvm_interface.h
- src/Chain/libraries/lvm/lvm_interface.cpp
> Revert "add storage into the dispacher cache"

- src/Chain/GRBit.vcxproj
- src/Chain/libraries/blockchain/ContractOperations.cpp
- src/Chain/libraries/contract/task_dispatcher.cpp
- src/Chain/libraries/include/contract/task_dispatcher.hpp
> Revert "add trx_evl_state in task_dispatcher to cache the statevalue"

- src/Chain/libraries/client/ContractApi.cpp
- src/Chain/libraries/contract/task_dispatcher.cpp
- src/Chain/libraries/glua/thinkyoung_lua_api.cpp
- src/Chain/libraries/glua/thinkyoung_lua_lib.cpp
- src/Chain/libraries/include/api/CommonApi.hpp
- src/Chain/libraries/include/blockchain/GluaChainApi.hpp
- src/Chain/libraries/include/contract/task.hpp
- src/Chain/libraries/include/contract/task_dispatcher.hpp
- src/Chain/libraries/include/glua/thinkyoung_lua_api.h
- src/Chain/libraries/include/rpc_stubs/CommonApiClient.hpp
- src/Chain/libraries/include/rpc_stubs/CommonApiOverrides.ipp
- src/Chain/libraries/include/rpc_stubs/CommonApiRpcClient.hpp
- src/Chain/libraries/include/rpc_stubs/CommonApiRpcServer.hpp
- src/Chain/libraries/include/wallet/Wallet.hpp
- src/Chain/libraries/rpc_stubs/CommonApiClient.cpp
- src/Chain/libraries/rpc_stubs/CommonApiRpcClient.cpp
- src/Chain/libraries/rpc_stubs/CommonApiRpcServer.cpp
- src/Chain/libraries/wallet/Wallet.cpp
Merge branch 'contract_refactor_main' into contract_refactor
> Contract refactor

- src/Chain/libraries/client/BlockchainApi.cpp
- src/Chain/libraries/client/NetworkApi.cpp
- src/Chain/libraries/include/api/CommonApi.hpp
- src/Chain/libraries/include/blockchain/Transaction.hpp
- src/Chain/libraries/include/rpc_stubs/CommonApiClient.hpp
- src/Chain/libraries/include/rpc_stubs/CommonApiOverrides.ipp
- src/Chain/libraries/include/rpc_stubs/CommonApiRpcClient.hpp
- src/Chain/libraries/include/rpc_stubs/CommonApiRpcServer.hpp
- src/Chain/libraries/rpc_stubs/CommonApiClient.cpp
- src/Chain/libraries/rpc_stubs/CommonApiRpcClient.cpp
- src/Chain/libraries/rpc_stubs/CommonApiRpcServer.cpp
add RPC blockchain_get_transaction_id
> add RPC blockchain_get_transaction_id

- deploy_tool/test.json
delegatename is only allowed small character
> delegatename is only allowed small character

- src/Chain/libraries/client/Client.cpp
> merge the pull request

- src/Chain/libraries/blockchain/ChainDatabase.cpp
- src/Chain/libraries/client/BlockchainApi.cpp
- src/Chain/libraries/include/api/CommonApi.hpp
- src/Chain/libraries/include/blockchain/ChainDatabase.hpp
- src/Chain/libraries/include/db/LevelPodMap.hpp
- src/Chain/libraries/include/net/Node.hpp
- src/Chain/libraries/include/net/PeerDatabase.hpp
- src/Chain/libraries/include/rpc_stubs/CommonApiClient.hpp
- src/Chain/libraries/include/rpc_stubs/CommonApiOverrides.ipp
- src/Chain/libraries/include/rpc_stubs/CommonApiRpcClient.hpp
- src/Chain/libraries/net/Node.cpp
- src/Chain/libraries/net/PeerDatabase.cpp
- src/Chain/libraries/rpc_stubs/CommonApiClient.cpp
- src/Chain/libraries/rpc_stubs/CommonApiRpcClient.cpp
- src/Chain/libraries/rpc_stubs/CommonApiRpcServer.cpp
add a arguement, makes the api can dump db once a time
> update api blockchain_dump_state   

- src/Chain/libraries/wallet/Wallet.cpp
cost_limit should less than 20000
> add call_contract cost limt

- BUILD_WIN32.md
- README.md
> merge the update

- src/Chain/libraries/blockchain/ChainDatabase.cpp
> merge the modification

- src/Chain/libraries/blockchain/ChainDatabase.cpp
- src/Chain/libraries/blockchain/Transaction.cpp
- src/Chain/libraries/include/blockchain/Transaction.hpp
> refactor the code 

- src/Chain/libraries/blockchain/ChainDatabase.cpp
- src/Chain/libraries/blockchain/ChainInterface.cpp
- src/Chain/libraries/client/Client.cpp
> refactor code

- src/Chain/libraries/blockchain/Transaction.cpp
> asset_issue
